deploy_timeout: 3600
name: "sert-cluster"
gui_config_file: /tmp/cfg.yaml

log_settings: logging.yaml
config_file: /tmp/netconfig.yaml

report:
  mail:
    smtp_server: "smtp.gmail.com"
    mail_to: "lht-sert-results@mirantis.com"
    mail_from: "lht-sert-results@mirantis.com"
    login: "lht-sert-results@mirantis.com"

cluster_desc:
    name: "certification_cluster"
    deployment_mode: "multinode"
    settings: 
        net_provider: "nova_network"
    release: "1"

